name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: HRKU-9dd1f38c-a9e1-428b-8973-3b3c81f28a58
          heroku_app_name: luffynewtxt545
          heroku_email: gohilkanubhai1980@gmail.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
